### ISSUE TITLE
Convert sample Python scripts to Python 3

### ISSUE THREAD

**Issue by mjpieters** [facebook/ThreatExchange#162]
Python 2 is legacy; please convert the existing sample scripts to Python 3 (3.5 and up?)

**Comment by tehmas** [comment]
If the ThreatExchange teams is okay with this, I would like to work on it.

**Comment by mgoffin** [comment]
I would suggest, instead of converting them to Python 3.x only, that they have backwards compatibility with 2.7.x. Yes it is legacy, but unfortunately the vast majority of tools and libraries out there are 2.x and is still something necessary to support for most any organization leveraging security tools built in Python.

This is the main reason why pytx has support for 2.7.x and 3.x (though it's untested past 3.4 because last time I tried to use 3.5 TravisCI failed because it had no 3.5 environments to build and test in).

There is also issue #34 which outlines the duplication of the scripts in the repo and the ones packaged with pytx. It would make sense to convert all of the scripts to using pytx and think about moving them into the pytx `scripts` directory as well.

**Comment by mjpieters** [comment]
Good point; is there any way for @tehmas to get in touch with you to work out what has priority here? Slack, IRC, email?

**Comment by mjpieters** [comment]
My apologies, this ticket is all based on a misundersstanding within FB. I'll close this for now.
