### ISSUE TITLE
store of tmk files

### ISSUE THREAD

**Issue by zzypeak** [facebook/ThreatExchange#326]
is there any suggestion to store tens of thourands tmk files for quickly read to memory? i'am wandering if mysql or hbase is proper for that.

**Comment by Dcallies** [comment]
Hey @zzypeak, I don't have any specific recommendations, but maybe I can guess at what will work best if you were building this into a service for efficient lookup. 

This information is mostly extrapolated from https://github.com/facebook/ThreatExchange/blob/master/hashing/hashing.pdf

TMK+PDQF hashes can be somewhat large (256kb), which may not work with some storage types. The type of operations are likely to just be serialized loading into memory (into maybe something like FAISS which supports efficient in-memory lookup), but there's also the useful property that the first 1kb of the hahes can be used to differentiate most videos. 

So a possible storage strategy might be to store one table with the first 1kb of each hash, mapping to an ID (or ids for collisions), which could be rapidly loaded into memory to bootstrap in-memory matching with the 1kb hashes, and then loading the longer 256kb hashes based on ids of matches from the 1kb hash.

Since its more efficient to do comparisons in memory, you only need to optimize for sequentually loading the first 1kb of the hashes, and then simple point lookups for the full hashes.

**Comment by zzypeak** [comment]
> lookups

thanks for reply. I'll have a try.
