### ISSUE TITLE
common.py/add_connection - not working

### ISSUE THREAD

**Issue by raajks2489** [facebook/ThreatExchange#43]
Please let us know once add_connection method works and share an example on how to use it.

**Comment by mgoffin** [comment]
The `.add_connection()` method works as you attempted to use it:

```python
instantiated_ti_object.add_connection(object_id_that_exists)
```

However, if `instantiated_ti_object` in this example is an object that hadn't previously existed in TX prior to you creating it and calling `.save()` we don't "reload" it properly. Here's the issue:

```python
new = ThreatIndicator()
new.set(TE.ThreatIndicator.STATUS,"MALICIOUS")
new.set(TE.ThreatIndicator.CONFIDENCE,"100")
new.set(TE.ThreatIndicator.TYPE,"URI")
new.set(TE.ThreatIndicator.INDICATOR, someurl)
# set the rest of the necessary stuff....
new.save() # HERE IS THE ISSUE
new.add_connection("object_id_that_exists_in_tx_already")
```

When you do `.save()`, TX will generate an Object ID and assign it to the new Threat Indicator. When we get the response from the server, we just return it to you. This means that your `new` object in this example doesn't have an `id` still and thus doesn't have a properly formatted `DETAILS` or `RELATED` URL attribute. So when you go to add a connection, it fails because the URL it uses is wrong.

What we should do is consume the server response on `.save()`, and if it is successful and contains an ID, set the ID on our object which should automatically set the URLs for us.

Thanks for catching this!

**Comment by mgoffin** [comment]
I have this ready to go if you'd like to test it:

https://github.com/facebook/ThreatExchange/commit/f4f1c0aef749577b7dea8db2383906ef60701c97

I haven't submitted it for a PR because I want the Travis PR to be accepted and going first before submitting any more code changes :)

**Comment by raajks2489** [comment]
You are right. It doesn't reload the object properly. So, I did something like the following after save():
result=new.save()
new2= ThreatIndicator.details(id=result['id'])
new2.add_connection(object_id_already_exists)

Thanks for looking into this. I will test the change sometime.

**Comment by mgoffin** [comment]
Thanks! if you test my changes please respond so we can get some input from more than just me! If it works out for you I can get a PR up and running eventually :)
