### ISSUE TITLE
Export ThreatExchange data in STIX/TAXI formats

### ISSUE THREAD

**Issue by jessek** [facebook/ThreatExchange#48]
Much of the community uses exchange formats like STIX and TAXI. We should create sample code which pulls data From ThreatExchange and converts it to these formats.

**Comment by jeffbryner** [comment]
And vice-versa: threat exchange (json) to STIX/TAXI (xml)

**Comment by mgoffin** [comment]
Some clarification points :)

- TAXII is (overgeneralizing here...) a set of libraries and standards for developing client/server interaction for exchanging messages which contain STIX content. Unless you're planning on exposing access to ThreatExchange via TAXII, this might not be necessary?

- STIX (and since we're dealing with Indicators, CybOX) should work pretty well here, especially with the new descriptors functionality coming out. Newer versions of the standards allow for "custom objects" which would help in defining things like the descriptors as well as any fields that aren't available in the standard or don't map well to one of their vocabularies.

- Along with STIX it might require the development of Profiles (https://stixproject.github.io/documentation/profiles/) so when people consume the STIX content they have a way to use the validator and also know what kind of stuffs are (possibly) in the document.

- pytx won't require much in the way of changes to support this. We should basically expose a way to request that the response format be in STIX, and then default to `full_response=True` (I don't think requiring libraries like lxml, pre-parsing the XML, building generators and such is the right move).

**Comment by hammem** [comment]
@mgoffin, do you want to chat more about this?  I think between the two of us, we could knock it out pretty quickly :)

**Comment by mgoffin** [comment]
@hammem sure!

**Comment by cwtaylor** [comment]
@hammem @mgoffin Has there been any update to this piece of work? This is something I would be very interested in.

**Comment by gmattson** [comment]
Yes, any progress on this or do we need to pick up this thread

**Comment by juliannagler** [comment]
To circle back here, this is not something we're currently focused on. It's a great example of space for the TE community to make a large impact, though. We've been asking our partners to contribute their translators and will post any updates to that end here. In the meantime, if you've got a translator you'd like to host in our repo, let us know!

**Comment by kruisdraad** [comment]
@juliannagler i am halfway for a (opensource/php) solution that stores locally in elasticsearch (accepts both API and Webhooks) as well as a bridge to MISP ... i also made fixes for the PHP scripts, can i just start sending PR's on this ... or do you have another way to go on this?

**Comment by hammem** [comment]
Bart, PRs would be great.  Happy to help get them merged in.
________________________________

**Comment by Dcallies** [comment]
Hey all, we're doing a bulk cleanup of the current state of the repo. By default we're closing all the old issues unless we're sure what the next steps are. Feel free to comment or re-open if this is still affecting you or you think something should happen.

```
               ...
             ;::::;
           ;::::; :;
         ;:::::'   :;
        ;:::::;     ;.
       ,:::::'       ;           OOO\
       ::::::;       ;          OOOOO\
       ;:::::;       ;         OOOOOOOO
      ,;::::::;     ;'         / OOOOOOO
    ;:::::::::`. ,,,;.        /  / DOOOOOO
  .';:::::::::::::::::;,     /  /     DOOOO
 ,::::::;::::::;;;;::::;,   /  /        DOOO
;`::::::`'::::::;;;::::: ,#/  /          DOOO
:`:::::::`;::::::;;::: ;::#  /            DOOO
::`:::::::`;:::::::: ;::::# /              DOO
`:`:::::::`;:::::: ;::::::#/               DOO
 :::`:::::::`;; ;:::::::::##                OO
 ::::`:::::::`;::::::::;:::#                OO
 `:::::`::::::::::::;'`:;::#                O
  `:::::`::::::::;' /  / `:#
   ::::::`:::::;'  /  /   `#
```
