### ISSUE TITLE
HMA Wiki: Add overview page

### ISSUE THREAD

**Issue by schatten** [facebook/ThreatExchange#606]
https://github.com/facebook/ThreatExchange/wiki/Overview

**Comment by Dcallies** [comment]
> Your user's content is private.
May want to extend to all platform data and not just the user.

All content from your platform and your users stay under your control. You can choose to upload your own data from HMA but it must first be configured to do so.

**Comment by mengyangwang** [comment]
is there a document to show the tech overview? Such as what technology that HMA uses, and what is the cost of HMA

**Comment by Dcallies** [comment]
Overall, it feels like this needs a graphic to explain HMA, with the key parts being:

1. The platform 
2. Content from the platform
3. External data store (datasets/threatexchange)
4. Results/actions
5. UI for inspecting results

**Comment by Dcallies** [comment]
Overall, having trouble with the header titles. Seems like they could be more generalized instead of being made specific. I.e.

Call your APIs when a match is found => Integrate HMA with your content moderation tools
Register your opinion when you do a human review => Contribute Reviews to Fight Digital Harm

**Comment by Dcallies** [comment]
To repeat a question asked during the meeting - who are the audience for this page?

**Comment by schatten** [comment]
This is for a non-technical audience. I expect this to be the first documentation page that people come across.
