### ISSUE TITLE
HMA Wiki: Settings Pages / ThreatExchange

### ISSUE THREAD

**Issue by mengyangwang** [facebook/ThreatExchange#614]
https://github.com/facebook/ThreatExchange/wiki/ThreatExchange-Setting-Page

@jeberl will review

**Comment by jeberl** [comment]
Requested Changed: 
- Capitalize terms that are in the glossary (Dataset, PrivacyGroup)
- Link to the glossary for once for each term in the glossary
- Under "Dataset Details" add a section describing what a Dataset is and what this page shows about a dataset
- Cleaned up a lot of the terminology. Not "hashing data", "Signals"
- "Writeback" isn't exactly the right term. It should be "Writeback Matches". Even if switched off the user can still Writeback TruePositive and FalsePositive. Can we change that on the site and here
- capitalize the start of each definition
- Changed some of the phrasing. Removed "dataset is in use" because its not clear what that means
