### ISSUE TITLE
HMA Wiki: Settings Pages / Action Rules

### ISSUE THREAD

**Issue by mengyangwang** [facebook/ThreatExchange#645]
https://github.com/facebook/ThreatExchange/wiki/The-Action-Rules-Page

@jeberl will review

**Comment by eriksendc** [comment]
1. Intro paragraph should be broken into multiple sentences (it's mostly in that form already).
2. Formatting on three sections: don't use a bulleted list at the top level. The instructions are short and can be a short 1-2 sentence paragraph.
3. Maybe a personal preference: make things bold that are to be selected (as opposed to using double quotes).
4. Use select instead of click.

**Comment by jeberl** [comment]
Requested Changes
- Can we add more about the logic that these rules apply. How exactly does an ActionRule Trigger an action. What feilds are available on the match for the ActionRule to read
- The ActionRules page has 2 fields that take super specific values `Labeled As` and `Not Labeled As`. We need to be super specific about what the format these fields take other wise this page is unuseable. Can you add detailed descriptions of what the json object looks like with different examples.
