### ISSUE TITLE
HMA Wiki: Concepts / What does HMA do with your media?

### ISSUE THREAD

**Issue by schatten** [facebook/ThreatExchange#647]
[Link to review](https://github.com/facebook/ThreatExchange/wiki/What-does-HMA-do-with-your-media%3F)

**Comment by BarrettOlson** [comment]
Review notes:
------------
nit: ~~It is the simplest to explain.~~ (it is the only example currently...)

image lists MD5 or TMK for video (might be worth mentioning we don't support video yet)

PDQ hashes ~~, checking equality is not enough.~~ allows us to check for distance not just equality 

"details (name, id and tags of the collaboration where the match was reported, match distance etc)" is confusing (and we don't propagate match distance because that is an index level detail (you can generate the distance if needed tho). 
possible alternative that I still don't love: "details (e.g. signal's id, tags, and the dataset(s) of the signal matched was found)"

Privacy section: link to a how to disable page.
