### ISSUE TITLE
HMA Wiki: Add installation page

### ISSUE THREAD

**Issue by jeberl** [facebook/ThreatExchange#677]
[wiki/Installation](https://github.com/facebook/ThreatExchange/wiki/Installation)

- [ ] Verify if public docker images can be used in lambdas
- [ ] If yes, update installation page with details
- [ ] If no, recommend docker as a dependency and show steps
[ ] Clean up makefile to only have installation related targets

**Comment by BarrettOlson** [comment]
I like it! Made a few minor edits that you should feel free to revert. 

I do think long term this is a little too much like CONTRIBUTING.md and can be made even more 'turn-key' 
However we aren't there yet. I do think having a way to use public images and avoid needing docker locally as @schatten 
suggested awhile ago, would be a good next step. 

Also, removed the "TODO: Create an ECR repository if it is not possible to use public docker images for lambdas." line as I think it is better suited to tracking here or in a new issue instead of the wiki itself.
